### ISSUE TITLE
Add support for BME280 sensor if possible ?

### ISSUE THREAD

**Issue by zanco** [DO4AS/jufo-project-radiosonde#1]
Hi, love the working FM APRS transmitter with the LoRa module. Cheap way to make a balloon payload for testing balloons vs float levels.

I would however like to have BME280 support, the BME680 is quite a bit more expensive and I happen to have 6 BME280 sensors around.

73'
Ben - PE2BZ

**Comment by DL9AS** [comment]
Hello Ben,

Thank you for your interest in my repo. The implementation of the BM280 sensor module is likely straight forward. An equivalent library to the BME680 is available for the BME280.

Unfortunately, I am currently on vacation and have very limited access to the internet and arduino compiler. In Addition, I do not have a BME280 to test with. Therefore, I will unfortunately not be able to add this feature in the next few weeks.

 If I get around to implementing this feature anyway, I will answer you.

For now, I encourage you to add this feature yourself.

Best wishes - 73

Amon Schumann - DO4AS
